INSERT INTO TODO(ID,TARGET_DATE,DESCRIPTION,USERNAME,DONE)
VALUES(1001,CURRENT_DATE(),'Learn AWS','rohan', false);

INSERT INTO TODO(ID,TARGET_DATE,DESCRIPTION,USERNAME,DONE)
VALUES(1002,CURRENT_DATE(),'Learn DevOps','rohan', false);

INSERT INTO TODO(ID,TARGET_DATE,DESCRIPTION,USERNAME,DONE)
VALUES(1003,CURRENT_DATE(),'Get a Job','rohan', false);